name: racconnect
description: "RACCONNECT App"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  pocketbase: ^0.22.0
  flutter_svg: ^2.1.0
  equatable: ^2.0.7
  lottie: ^2.6.0
  excel: ^4.0.6
  intl: ^0.20.2
  path: ^1.9.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  http: ^1.4.0
  share_plus: ^11.0.0
  google_fonts: ^6.2.1
  file_picker: ^10.2.0
  pdf: ^3.8.1
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cc icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/cc icon.png"
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: true
    image_path: "assets/images/cc icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/cc icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
